markdown: kramdown
local: false
name: pflouret.github.io
url: http://pflouret.github.io
description: pflouret.github.io = @parb = pablo flouret
author: pablo flouret
rss_path: /feeds/
rss_name: all.xml
gems:
    - jekyll-last-modified-at
